apiVersion: v1
kind: Pod
metadata:
  name: react-app
  namespace: react-app-ns
spec:
  containers:
  - name: react-app
    image: iamamash/react_django_demo_app:latest
    ports:
    - containerPort: 8000
